# Generated by Django 3.2.3 on 2021-12-01 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211201_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 13, 34, 31, 322948, tzinfo=utc)),
        ),
    ]
